# theme.toml template for a Hugo theme
# See http://carlosimoes.github.io/DeepNotes.github.io/ for an example

name = "PaperMod"
homepage = "http://carlosimoes.github.io/DeepNotes.github.io/"
tags = []
features = [
  "responsive",
  "single-column",
  "blog",
  "cover-image",
  "table-of-contents",
  "opengraph",
  "highlight.js",
  "favicon",
  "archive",
  "share-icons",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search"
]
min_version = "0.83.0"

[author]
  name = "Carlos Simões"
  homepage = "http://carlosimoes.github.io/DeepNotes.github.io/"


[params.profileMode]
enabled = true
title = "<Title>"
subtitle = "This is subtitle"
imageUrl = "<image link>"
imageTitle = "<title of image as alt>"
imageWidth = 120
imageHeight = 120

  [[params.profileMode.buttons]]
  name = "Archive"
  url = "/archive"

  [[params.profileMode.buttons]]
  name = "Github"
  url = "https://github.com/"

[[params.socialIcons]]
name = "<platform>"
url = "<link>"

[[params.socialIcons]]
name = "<platform 2>"
url = "<link2>"
