# theme.toml template for a Hugo theme
# See http://carlosimoes.github.io/DeepNotes.github.io/ for an example


baseURL = 'http://carlosimoes.github.io/DeepNotes.github.io/'
languageCode = 'en-us'
title = 'My Deep Notes'
metaDataFormat = "yaml"
theme = "PaperMod"

name = "PaperMod"
description = "My Deep Notes"
homepage = "http://carlosimoes.github.io/DeepNotes.github.io/"
tags = []
features = []
min_version = "0.83.0"

[author]
  name = "Carlos Simões"
  homepage = "https://github.com/carlosimoes/"