# theme.toml template for a Hugo theme
# See http://carlosimoes.github.io/DeepNotes.github.io/ for an example

name = "PaperMod"
homepage = "http://carlosimoes.github.io/DeepNotes.github.io/"
tags = []
features = [
  "responsive",
  "single-column",
  "blog",
  "cover-image",
  "table-of-contents",
  "opengraph",
  "highlight.js",
  "favicon",
  "archive",
  "share-icons",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search"
]
min_version = "0.83.0"

[author]
  name = "Carlos Simões"
  homepage = "http://carlosimoes.github.io/DeepNotes.github.io/"


[params]
    profileMode = [
        enabled = true
        title = "My Deep Notes" # optional default will be site title
        subtitle = "Welcome to my blog on deep learning!
Deep learning is a subfield of machine learning that is inspired by the structure and function of the brain, specifically the neural networks that make up the brain. It involves training artificial neural networks on a large dataset, allowing the network to learn and make intelligent decisions on its own.
In these notes, you will find a collection of my thoughts and musings as I delve into the world of deep learning."
        imageUrl = "<image link>" # optional
        imageTitle = "<title of image as alt>" # optional
        imageWidth = 120 # custom size
        imageHeight = 120 # custom size
        buttons =
            - name= Archive
            url= "/archive"
            - name= Github
            url= "https://github.com/"
      ]

    socialIcons: # optional
        - name: "<platform>"
            url: "<link>"
        - name: "<platform 2>"
            url: "<link2>"